### ISSUE TITLE
HTML tags not rendered in the latest version

### ISSUE THREAD

**Issue by peilingjiang** [alex-shpak/hugo-book#109]

**Comment by alex-shpak** [comment]
Hi!
Hugo 0.60 migrated to Goldmark, so likely you need to enable unsafe mode for it.
https://gohugo.io/news/0.60.0-relnotes/
```yaml
markup:
  goldmark:
    renderer:
      unsafe: true
```
