### ISSUE TITLE
Use the root directory instead of docs for documents

### ISSUE THREAD

**Issue by boramalper** [alex-shpak/hugo-book#157]
Hi and thanks for the amazing theme!

I couldn't figure out how to use the root directory (i.e. `content/`) for my documents instead of `content/docs/`. Sorry for this simple question, but I would really appreciate some help.

So far I have tried the following with no success:
```
BookSection = "*"
BookSection = ""
# BookSection = "*"
```

Regards,
Bora

**Comment by alex-shpak** [comment]
Hi!
`BookSection = '*'` should do the trick.

One thing you need to know: Hugo assigns templates to pages based on `section` name. For example content in `docs` folder has `type: docs`.
So if you use `BookSection = '*'` you need to give `type: docs` to pages outside of `docs` folder.

I tried `*` on `exampleSite`, seems like it works.
For reference: https://gohugo.io/templates/lookup-order/

**Comment by boramalper** [comment]
Hi again!

How would my URLs look like in this case? Still `http://example.com/docs/title`? Perhaps I should have been clearer that I am trying to get rid of "docs" in the URL.

**Comment by alex-shpak** [comment]
Hi again! `docs` in URL refer to folder `docs/` so you will need to move files out.
As I mentioned then you will need to have frontmatter at the beginning of markdown files. 

```
---
type: docs
---
```

**Comment by alex-shpak** [comment]
I made some changes, `docs` template is applied by default now. Initial idea was to not interfere with user's templates, but seems like it is not often used (if used at all).

So no need for `type: docs` then.

**Comment by boramalper** [comment]
Thank you so much for this! Although I can now confirm that the URL is as intended, the menu is still empty... 

I am using the latest (050d5a83de701af6e8bc20a90e1de5ab9ce95356) commit on the master branch, Hugo v0.65.3-211BA42A/extended linux/amd64.

My directory looks like this (omitting public):
```
.
├── archetypes
│   └── default.md
├── config.toml
├── content
│   ├── filtering-e-mails.md
│   └── _index.md
├── data
├── layouts
├── resources
│   └── _gen
├── static
└── themes
    └── hugo-book
```

`config.toml`
```toml
baseURL = "https://support.newsmail.today/"
languageCode = "en-gb"
title = "newsmail.today Support"
theme = "hugo-book"

# Theme config

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

enableGitInfo = true

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[params]
  BookToC = true
  BookSection = "*"
  BookDateFormat = '2 Jan 2006'
  BookSearch = true
  BookComments = false
```

head `filtering-e-mails.md`
```markdown
---
title: Filtering E-Mails
weight: 1
---
# Filtering E-Mails
If you are receving too many e-mails from us, or find it distracting to see the items
[...]
```
