### ISSUE TITLE
Change language of displayed dates

### ISSUE THREAD

**Issue by VilhelmPrytz** [alex-shpak/hugo-book#162]
Is it possible to change the language of which dates (such as the "Last modified" date) is displayed (e.g. from English to Swedish)?

Thanks!

**Comment by alex-shpak** [comment]
Hm, I don't think there is an easy way. It uses https://gohugo.io/functions/dateformat/ function to present date, and seems like at the moment it doesn't support language change.

Check discussion here: https://discourse.gohugo.io/t/dates-only-in-english/1317

**Comment by VilhelmPrytz** [comment]
Thanks for the discussion link. I guess I could do something like [this](https://discourse.gohugo.io/t/dates-only-in-english/1317/10) but then I'd have to inject to the first `<div>` in `layouts/partials/docs/footer.html` and I'm not really sure how to do that?

Perhaps [this](https://discourse.gohugo.io/t/dates-only-in-english/1317/40) could be interesting for the `i18n`?

**Comment by alex-shpak** [comment]
For changing `layouts/partials/docs/footer.html` you will have unfortunately copy-paste template template.

For some of this solutions I fell like I would not have enough time supporting multiple languages, so I think there are few options:
1. Switch to only numeric format:  eg `YYYY-MM-DD`
2. Maybe we can make `date-format.html` partial, so you can override it to print dates as you want.

**Comment by VilhelmPrytz** [comment]
I think a `date-format.html` partial would be a good idea!

**Comment by alex-shpak** [comment]
Hi!
I added `docs/date.html` partial that used thought them, so now you can customize it.

**Comment by VilhelmPrytz** [comment]
Nice! How do I use it?

**Comment by alex-shpak** [comment]
Create `layouts/partials/docs/date.html` in your site.
https://github.com/alex-shpak/hugo-book/blob/master/layouts/partials/docs/date.html

It receives `.Data` and `.Format` variables as context. And then you can `return` string value of date how you want it.
Tho, I just realised maybe you want to have access to `.Site` variable. To get `i11n` data? Or you can hardcode month names in partial itself?

**Comment by VilhelmPrytz** [comment]
Yes, the best thing would be if this can be changed from the `i11n` config. I would happily translate it for Swedish.

The `footer.html` partial is in `layouts/partials/docs/inject` and this partial is just in `layouts/partials/docs`. Any particular reason for this?

**Comment by alex-shpak** [comment]
Inject partials are meant to be empty for user to override. Basically to inject some HTML into specific place. On the other hand `partials/docs/...` partials - templates that are part of layout, including `date` formatting partial.

I will change that interface to `{{ partial "docs/date" (dict "Date" .Date "Site" .Site) }}`
Date partial doesn't include translation logic in it from theme, but you can put [that trick](https://discourse.gohugo.io/t/dates-only-in-english/1317/10) there yourself.

🤦 I mistyped i11n, should be i18n.

**Comment by VilhelmPrytz** [comment]
Hmm, so if I make the `partial` return `{{ index $mymonths .Date.Month }}`, where do I define `mymonths`? Sorry if I am not making sense, I am not that familiar with Hugo nor Go.

**Comment by alex-shpak** [comment]
I hacked some example together.
In `i18n/sv.yaml` add:
```yaml

- id: January
  translation: Januari
- id: February
  translation: Februari
- id: March
  translation: Mars
- id: April
  translation: April
- id: May
  translation: Maj
- id: June
  translation: Juni
- id: July
  translation: Juli
- id: August
  translation: Augusti
- id: September
  translation: September
- id: October
  translation: Oktober
- id: November
  translation: November
- id: December
  translation: December
```

and then in `layouts/partials/docs/date.html` get translated month name and format date. 
```tpl
{{- $month := default .Date.Month (i18n .Date.Month) -}}
{{- return (printf "%s %d, %d" $month .Date.Day .Date.Year) -}}
```
