### ISSUE TITLE
Multi-Language and BookEditPath

### ISSUE THREAD

**Issue by tyler71** [alex-shpak/hugo-book#200]
``` yaml
languages:
  en:
    languageName: English
    contentDir: content/en
    weight: 1
  al:
    languageName: AnotherLanguage
    contentDir: content/al
    weight: 1
```

I have content in `content/en` and `content/al`
I had the BookEditPath set to `blob/master/content` but that brings up 

`https://github.com/user/repo/blob/master/content/_index.md`
Where it should show
`https://github.com/user/repo/blob/master/content/en/_index.md`

Is the `Edit this page` functionality possible with multi-language?
