### ISSUE TITLE
How-to Fixed header and footer

### ISSUE THREAD

**Issue by alextavu** [alex-shpak/hugo-book#229]
Hi 
Thank you a lot for this theme, I wish I found it sooner.
An issue in my case however: how to fixed to top the header and to bottom the footer ?
I found it particularily annoying to have to swipe back to the top to get access to the Menu or the ToC labels on small screens.
Bottom, cause I need to have something there at anytime.

My attemps in the css destroyed the whole page.. You should be able to be faster than me on resolving this case.

Thank you if you can help me in this.

**Comment by alex-shpak** [comment]
Hi!
I don't have solution out of the box, mostly because of way how fixed left and right menus are working. I would suggest to try:
1. `position: sticky` for mobile header.
2. Use `inject/footer.html` to add footer menu, and give it also `position: sticky` 

But both menus will have width of content. Something to node, `body` has `overflow-x: hidden` that might cause some troubles with fixes/sticky positioning.

**Comment by alex-shpak** [comment]
Hi!
I made little change in CSS, it should let you use `position: sticky` on header or footer.

to try add `assets/_custom.scss`
```scss
@mixin sticky {
  margin: -$padding-16;
  padding: $padding-16;
  margin-bottom: 0;

  background: $body-background;
  position: sticky;
  top: 0;
}

.book-header {
  @include sticky;
  top: 0;
  z-index: 1;
}

.book-footer {
  @include sticky;
  bottom: 0;
  z-index: 1;
}
```
