### ISSUE TITLE
Netlify CMS Support

### ISSUE THREAD

**Issue by alex-shpak** [alex-shpak/hugo-book#248]
A note for future:

Recently NetlifyCMS added support for nested collections: https://github.com/netlify/netlify-cms/pull/3716
That means netlifycms admin panel can be used to manage this theme content, it will require some shuffle in content structure because `name.md` files are not supported, only folder structure with `_index.md` files is.

Example config:
```yaml
backend:
  # ...

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "document"
    label: "Documents"
    label_singular: "Document"
    folder: "content/docs"
    create: true
    nested: { depth: 10 }
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "docs" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
    meta: { path: { widget: string, label: 'Path', index_file: '_index' } }

  - name: "post"
    label: "Posts"
    label_singular: "Post"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "posts" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
```
