### ISSUE TITLE
How to add another translation?

### ISSUE THREAD

**Issue by Nagidal** [alex-shpak/hugo-book#249]
I would like to add Czech to the hugo-book translations. How do I do that? I have created `themes/hugo-book/i18n/cs.yaml` and translated the words analogous to the other yaml files in that directory. But this doesn't seem to be enough. I also updated `config.yaml` of the main site with this:

```
DefaultContentLanguage: en

languages:
  en:
    - languageName: English
    - weight: 1
  cs:
    - languageName: Česky
    - weight: 2
```

When the server starts, it shows the site with the language hover-over menu, but this menu has an empty string instead of displaying the language name "Česky".

When I create `*.cs.md` files, it correctly finds and links them. It's just that one cannot see the language's name in the translations menu.
