### ISSUE TITLE
Columns make mobile pages have very thin text

### ISSUE THREAD

**Issue by VegaDeftwing** [alex-shpak/hugo-book#298]
I'm far from knowing my way around web-dev, but I think adding this `@media screen and ...` section to _shortcodes.scss fixes it reasonably well, by just rendering what would have been in the split below. It's not great, but at least it prevents mobile pages from having like 20 character wide columns.

Submitting as issue instead of PR as I suspect this css can be written significantly better as to not re-define so much. 
```scss
  // {{< columns >}}

  .book-columns {
    margin-left: -$padding-16;
    margin-right: -$padding-16;

    > div {
      margin: $padding-16 0;
      min-width: $body-min-width / 2;
      padding: 0 $padding-16;
    }
  }

  @media screen and (max-width: $mobile-breakpoint) {
    .book-columns {
      margin-left: -$padding-16;
      margin-right: -$padding-16;
  
      > div {
        margin: $padding-16 0;
        // Setting this to not be /2 makes this work on mobile.
        min-width: $body-min-width; 
        padding: 0 $padding-16;
      }
    }
  }
```
