### ISSUE TITLE
Setting max-width but not height screws up some images

### ISSUE THREAD

**Issue by chrillek** [alex-shpak/hugo-book#374]
The default style sheet does this:
```css
.markdown img {
  max-width: 100%;
}
```
This screws up some images at least on a current iPhone, because it adjusts the width while the height remains constant.
Changing this to
```css
.markdown img {
  max-width: 100%;
 height: auto;
}
```
removes the problem.
