### ISSUE TITLE
missing style when deploy to github pages

### ISSUE THREAD

**Issue by lemuellew** [alex-shpak/hugo-book#381]
# local 
`hugo server -D`

![image](https://user-images.githubusercontent.com/59448437/132814959-4addc52f-7a6a-450d-9171-2b55f0974515.png)

# github pages
![image](https://user-images.githubusercontent.com/59448437/132815003-4b8f358d-b0b5-4ef1-bee7-91476c5966fb.png)

# workflows/gh-pages.yml
``` yml
name: GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
