### ISSUE TITLE
Hugo module install fails 

### ISSUE THREAD

**Issue by kurttheviking** [alex-shpak/hugo-book#382]
Just downloaded the latest version of hugo and attempted to setup a new site with hugo-book as a hugo module but was unable to start local server. Repro...

1. `cd ~`
2. `hugo new site test`
3. `cd test`
4. edit `config.toml` to add the following:

```toml
[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
```
Then, run:

5. `hugo mod get -u`
6. `hugo server --minify`

hugo fails with the following:

```
Error: module "github.com/alex-shpak/hugo-book" not found; either add it as a Hugo Module or store it in "/home/<username>/test/themes".: module does not exist
```

`hugo env` shows:

```
hugo v0.88.1-5BC54738 linux/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.16.7"
```
