### ISSUE TITLE
Center images

### ISSUE THREAD

**Issue by nleiva** [alex-shpak/hugo-book#383]
Hi, 

Any chance you could add an option to center images. Something like (`assets/_markdown.scss`):

```css
  img {
    display: block;
    margin-left: auto;
    margin-right: auto;
    max-width: 100%;
    height: auto;
  }
```

Thanks

**Comment by alex-shpak** [comment]
Hi!
If needed you can add it to your site.
In your repository create file `assets/_custom.scss`, there you can specify custom CSS you want. Just make sure to place it under `.markdown {}` selector to not affect icons

**Comment by nleiva** [comment]
Thank you! I'll look into this.

**Comment by nleiva** [comment]
Problem solved! I added this to file `_custom.scss` in the `$PROJECT/assets/` folder

```css
.markdown img { 
    display: block;
    margin-left: auto;
    margin-right: auto;
    max-width: 100%;
    height: auto;
}
```

Thanks
