### ISSUE TITLE
Translating Language Names

### ISSUE THREAD

**Issue by nnzv** [alex-shpak/hugo-book#562]
Hi there,

I'm using `hugo-book` theme for personal experiments, and I have a question about translating language names. 

Here's what's in my setup:

```toml
[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content.en'
  weight = 1

[languages.es]
  languageName = 'Spanish'
  contentDir = 'content.es'
  weight = 2
```

When I switch to Spanish, the menu still shows 'Spanish' instead of 'Español' (the translation from English to Spanish). 

Is there a way to make it automatically show the right language name based on the chosen language? I think this would make things better for websites with different languages.
