### ISSUE TITLE
markup highlight not work

### ISSUE THREAD

**Issue by try-agaaain** [alex-shpak/hugo-book#608]
I generated the `manni` style with `hugo gen chromastyles --style=manni> assets/manni.css` and added the following code in [config.yaml](https://github.com/try-agaaain/try-agaaain/blob/cb7a357f7b31d8155ac7bf30d85c3f3e0609c08d/config.yaml#L7-L11):

```yaml
markup:
  highlight:
    noClasses: true
    style: manni
    tabWidth: 4
```

However, frustratingly, no matter how I adjust it, the code formatting does not change to ABAP style, and the background color of the code block remains black.

Here is my code repository: [blog](https://github.com/try-agaaain/try-agaaain/tree/main). Could you please help me see what went wrong?

**Comment by try-agaaain** [comment]
I found that there was another `markup` identifier originally existing in `config.yaml`, which I overlooked, as shown below:
```yaml
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
```
After merging these two `markup` configurations, syntax highlighting for code blocks works fine.
