### ISSUE TITLE
Adding copy to clipboard support for highlight code blocks

### ISSUE THREAD

**Issue by djsamperi** [alex-shpak/hugo-book#616]
It would be helpful to have support for copy-to-clipboard button for fenced code blocks in
the hugo-book theme. There is a discussion on how to do this here:
https://discourse.gohugo.io/t/copy-to-clipboard-from-code-highlight-context/49633.
I managed to get the simpler (older) strategy working with hugo-book , but
not the one recommended by jmooring that employs Node.js.

**Comment by alex-shpak** [comment]
Hi!
I looked into adding copy button before, but as I try to keep everything simple I decided against it, it was too much of support for icons, code and light-dark theme,
But I can reconsider is simple (code wise) solution with arise.

**Comment by eskopp** [comment]
Hello @alex-shpak  and @djsamperi,
I had the same problem. I made the following solution myself. The implementation is quite simple and so is the layout. Maybe you can add it to the original repo. 
Greetings
@eskopp


# Solution
## Dark
![image](https://github.com/alex-shpak/hugo-book/assets/129506395/375b41a1-d6e0-43e5-80c1-034323956ab2)

## Light
![image](https://github.com/alex-shpak/hugo-book/assets/129506395/9b6ecbc3-7eee-4d35-bc1f-144da19ae6f2)



# Source Code
## JavaScript Code
```js
<script>
  document.addEventListener('DOMContentLoaded', (event) => {
    document.querySelectorAll('pre code').forEach((block) => {
      const button = document.createElement('button');
      button.className = 'copy-button';
      button.textContent = 'Copy';
      button.addEventListener('click', () => {
        const range = document.createRange();
        range.selectNodeContents(block);
        const selection = window.getSelection();
        selection.removeAllRanges();
        selection.addRange(range);
        document.execCommand('copy');
        button.textContent = 'Copied!';
        setTimeout(() => { button.textContent = 'Copy'; }, 2000);
      });
      block.parentNode.insertBefore(button, block);
    });
  });
  </script>
```

## CSS Code
```css
.copy-button {
  position: absolute;
  right: 10px;
  top: 10px;
  padding: 5px 10px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  background-color: #6c757d;
  color: white;
  font-family: Arial, sans-serif;
  font-size: 0.875rem;
  box-shadow: 0 2px 4px rgba(0,0,0,0.15);
  transition: background-color 0.3s, box-shadow 0.3s;
}

.copy-button:hover {
  background-color: #5a6268;
  box-shadow: 0 2px 5px rgba(0,0,0,0.25);
}

pre {
  position: relative;
  background-color: #f8f9fa;
  border: 1px solid #e1e1e1;
  padding: 16px;
  border-radius: 4px;
  overflow: auto;
}
```
