### ISSUE TITLE
"Edit this page" links broken by absolute file paths

### ISSUE THREAD

**Issue by vossenjp** [alex-shpak/hugo-book#725]
In Hugo v0.147.4 the `strings.TrimPrefix hugo.WorkingDir .Page.File.Filename` code in `hugo-book/layouts/partials/docs/links/edit.html` does not work, so you end up with broken links like:
* Need: `repos/bcp/browse/BCP/wiki2/docs/`
* Bad:  `repos/bcp/browse/home/user/repos/BCP/wiki2/docs/`
Note the `/home/user/repos` part is not wanted and should be removed by `strings.TrimPrefix hugo.WorkingDir` but isn't.

The fix is to change `.Page.File.Filename` to `.File.Path`.

In the meantime, the clean work-around is to create (note `hugo`, not `hugo-book`!) `layouts/partials/docs/links/edit.html` with:
```
{{- $bookFilePath := (strings.TrimPrefix hugo.WorkingDir .File.Path | path.Join) -}}
{{- .Site.Params.BookRepo }}/{{ .Site.Params.BookEditPath }}{{ ($bookFilePath) -}}
```

The above clean work-around works as expected and desired in v0.145.0, which I require for right now due to #708.  :-(  I have not tested this with any versions other than v0.147.4 and v0.145.0.

**Comment by vossenjp** [comment]
I suspect `module.mounts` may be the culprit.  As I said, the fix for me is to change `.Page.File.Filename` to `.File.Path` in `hugo-book/layouts/_partials/docs/links/edit.html`.

## Steps to reproduce

1. Using `hugo_extended_0.147.4_Linux-64bit` on Linux Mint 21.3
1. `hugo new site url-test`
1. `cd url-test`
1. `git init`
1. `git add .`
1. `git commit -m 'first commit'`
1. `git submodule add https://github.com/alex-shpak/hugo-book themes/hugo-book`
1. `git commit -m 'added hugo-book submodule'`
	* Note, using: f2c703e
1. `vi hugo.toml` # see below
1. `../hugo server`
	* Ignore a bunch of "WARN  Raw HTML omitted" warnings
1. Browse to <http://localhost:1313/content.en/posts/>
	1. "Edit this page" link is: https://go.to.example.org/repository/projects/code/browse//themes/hugo-book/exampleSite/content.en/posts/_index.md
		1. Note the incorrect "/themes/hugo-book/exampleSite/" part
1. `mkdir -p layouts/partials/docs/links`
1. `cp themes/hugo-book/layouts/_partials/docs/links/edit.html layouts/partials/docs/links`
1. `perl -i -pe 's/ \.Page\.File\.Filename / .File.Path /;' layouts/partials/docs/links/edit.html`
1. `../hugo server`
	* Ignore a bunch of "WARN  Raw HTML omitted" warnings
1. Browse to <http://localhost:1313/content.en/posts/>
	1. "Edit this page" link is now correct: https://go.to.example.org/repository/projects/code/browse/content.en/posts/_index.md
		1. Note the incorrect "/themes/hugo-book/exampleSite/" part is now absent.

### `hugo.toml`

```toml
# For "Edit this page" links broken by absolute file paths #725
baseURL = 'https://go.to.example.org/'
languageCode = 'en-us'
title = 'My Edit Links Test Site'

theme = 'hugo-book'

enableGitInfo = true

[module]
  [[module.mounts]]
    source = 'themes/hugo-book/exampleSite'
    target = 'content'

[params]
  BookToC = true

  BookRepo = 'https://go.to.example.org/repository/projects/code'
  BookCommitPath = 'commits'
  BookEditPath = 'browse/'
```
