### ISSUE TITLE
Consider removing link and image render hooks in favor of embedded hooks

### ISSUE THREAD

**Issue by jmooring** [alex-shpak/hugo-book#731]
This would also eliminate the `BookPortableLinks` parameter.

- <https://gohugo.io/render-hooks/links/#default>
- <https://gohugo.io/render-hooks/images/#default>

Instead of setting `BookPortableLinks` to `true`, site authors would place this in their site config:

```toml
[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true
```

**Note that these hooks are automatically enabled for multilingual single-host sites, provided they are not overridden by the theme.**

If site authors have placed resources in the `static` directory, and they are unable or unwilling to move them to the `assets` directory, they must mount the `static` directory to the `assets` directory by including both of these entries in their site configuration:

```toml
[[module.mounts]]
  source = 'assets'
  target = 'assets'

[[module.mounts]]
  source = 'static'
  target = 'assets'
```

Note that they need to create these mounts anyway to use the embedded figure shortcode when their site is served from a subdirectory and the resources are in the `static` directory.

In a future Hugo release users will be able to override theme link and image render hooks with the embedded hooks:
<https://github.com/gohugoio/hugo/issues/13535>

Justification for making this change:
- You are making portable links/images somebody else's problem
- It's a step towards consistent portable links/images across the Hugo universe
- It makes supporting this theme just a little bit easier (see this [forum topic](https://discourse.gohugo.io/t/baseurl-problem-when-running-with-docker-compose/55086))

Reference: <https://discourse.gohugo.io/t/55087>
