### ISSUE TITLE
How to add TOC NUMBER Style to section title

### ISSUE THREAD

**Issue by elegist** [alex-shpak/hugo-book#78]
Hi, many thanks to your interesting work. I think we should add toc number to book theme. Style like this plugin in hexo [see this page](https://github.com/r12f/hexo-heading-index) and [this page](http://r12f.com/posts/adding-index-to-your-headings-with-hexo-heading-index/).

**Comment by alex-shpak** [comment]
Hi!

I didn't find nice way to implement this in hugo except doing js, which I try to avoid in this theme.
I think you can either add your custom script in `partials/docs/inject/head.html` or have a bash script or something similar to set numbers for headings.

So it's `wontfix` for now.

**Comment by elegist** [comment]
Thanks for your reply. I found the CSS 'counter-reset' properity can add toc number. It's available for me...

**Comment by alex-shpak** [comment]
Yeah, `counter-reset` can work, with some `:before` content for headings.

**Comment by alex-shpak** [comment]
This, added to `_custom.scss` probably should do.
```scss
.markdown {
  @for $h from 1 through 6 {
    h#{$h} {
      counter-increment: h#{$h};
      counter-reset: h#{$h + 1};

      $content: '';
      @for $n from 1 through $h {
        $content: $content + 'counter(h#{$n})"."';
      }

      &::before {
        content: unquote($content) ' ';
      }
    }
  }
}

.book-toc nav ul {
  list-style: decimal;
}
```
